# Levels for disease status
# S = Susceptible
# PS = Infected, presymptomatic
# IS = Infected, symptomatic
# IA = Infected, asymptomatic 
# R = Recovered

# ============================================================================ # 
# Incubation period
# ---------------------------------------------------------------------------- #
# Input:
# n = Number of values to be generated by the distribution
# shape = shape of gamma distribution
# scale = scale of gamma distribution
# Output:
# n values drawn from incubation period distribution
inc.period <- function(n=1, shape=1.58, scale=7.11){
  # return(rweibull(n, shape=1.58, scale=7.11)) # Alpha
  return(rweibull(n, shape=1.58, scale=3)) # Omicron
  # return(rgamma(n, shape=5.807, scale=0.948))
}

prop.symp <- function(n=1, teacher=T, vaccination_flag=F, scaling_factor=scaling_prop_symp){
  if(teacher) prop_symp <- runif(n, min=min(0.75*scaling_factor, 1), max=min(0.83*scaling_factor, 1))
  else prop_symp <- runif(n, min=min(0.4*scaling_factor, 1), max=min(0.85*scaling_factor, 1))
  if(any(is.na(prop_symp))){
    print(paste0("NA in prop.symp function. scaling factor = ", scaling_factor))
  }
  return(prop_symp)
}

# Relative infectiousness of asymptomatic infections
asymp.scale <- function(n=1, min=0.3, max=0.7){
  return(runif(n, min=min, max=max))
}

# Relative susceptibility for students
susc.scale <- function(n=1, mean=0.64, sd=0.09){
  return(rtruncnorm(n, a=0, mean=mean, sd=sd))
}

# Relative infectivity for students
infec.scale <- function(n=1, mean=0.85, sd=0.1){
  return(rtruncnorm(n, a=0, mean=mean, sd=sd))
}

# Relative infectivity depending on type of contact
contact.infec.scale <- function(n=1, min=0.5, max=0.85){
  return(runif(n, min=min, max=max))
}


infectiousness <- function(t, scaling=1.0, R_0=R0){
  # gen_time <- dweibull(t, shape=1.6, scale=6.84) # Alpha and Delta
  gen_time <- dgamma(t, shape=0.6639232, scale=3.313636) # omicron
  infectivity <- ifelse(gen_time*R_0*scaling>=0 & !is.infinite(gen_time), gen_time*R_0*scaling, 0)
  return(max(0, infectivity))
}

infectiousness_vacc <- function(t, R_0=R0, vacc_red = rel_inf, tol=1e-5){
  # gen_time <- vacc_red*dweibull(t, shape=1.6, scale=6.84)
  gen_time <- vacc_red*dgamma(t, shape=0.6639232, scale=3.313636) # omicron
  infectivity <- ifelse(gen_time*R_0*scaling>=0 & !is.infinite(gen_time), gen_time*R_0*scaling, 0)
  return(max(0, infectivity))
}

# Relative susceptibility of vaccinated individuals
susc.vacc.scale <- function(n=1, min=1-0.9, max=1-0.78){
  if(n<=0) return(numeric(0))
  else return(runif(n, min=min, max=max))
}

prob.trans <- function(time, infec=T, susc=F, asymp=F, vacc=F, R_0=R0){
  if(vacc) infectivity <- infectiousness_vacc(t=time, R_0=R_0)
  else infectivity <- infectiousness(t=time, R_0=R_0)

  prob_trans <- infectivity*ifelse(infec, infec.scale(), 1)*ifelse(asymp, asymp.scale(), 1)
  return(max(0, prob_trans))
}
